name: Deploy ECS

on:
  push:
    branches:
      - main


jobs:

  deploy:

    permissions:

      id-token: write

      contents: read

    runs-on: ubuntu-latest
    
    
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.AWS_ROLE }}

      - name: Login ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Image
        run: |
          docker build -t app ./app

      - name: Push Image
        run: |
          docker tag app:latest 344211401727.dkr.ecr.us-east-1.amazonaws.com/log-analytics-repo:latest
          docker push 344211401727.dkr.ecr.us-east-1.amazonaws.com/log-analytics-repo:latest

      - name: Force Deployment
        run: |
          aws ecs update-service \
          --cluster log-analytics-cluster \
          --service log-analytics-service \
          --force-new-deployment